---
- import_tasks: preflight.yml

- import_tasks: install.yml
  when: (not __node_exporter_is_installed.stat.exists) or (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version)
  become: true

- import_tasks: configure.yml
  become: true

- name: Ensure Node Exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  become: true